
package fr.imie.bankocash.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BankocashSoapService", targetNamespace = "http://soap.bankocash.imie.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankocashSoapService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createCompte", targetNamespace = "http://soap.bankocash.imie.fr/", className = "fr.imie.bankocash.soap.CreateCompte")
    @ResponseWrapper(localName = "createCompteResponse", targetNamespace = "http://soap.bankocash.imie.fr/", className = "fr.imie.bankocash.soap.CreateCompteResponse")
    public void createCompte(
        @WebParam(name = "arg0", targetNamespace = "")
        CompteEntity arg0);

}
