
package fr.imie.bankocash.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BankocashSoapService", targetNamespace = "http://soap.bankocash.imie.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankocashSoapService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns fr.imie.bankocash.soap.CompteEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "debiteCompte", targetNamespace = "http://soap.bankocash.imie.fr/", className = "fr.imie.bankocash.soap.DebiteCompte")
    @ResponseWrapper(localName = "debiteCompteResponse", targetNamespace = "http://soap.bankocash.imie.fr/", className = "fr.imie.bankocash.soap.DebiteCompteResponse")
    public CompteEntity debiteCompte(
        @WebParam(name = "arg0", targetNamespace = "")
        CompteEntity arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Float arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns fr.imie.bankocash.soap.CompteEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crediteCompte", targetNamespace = "http://soap.bankocash.imie.fr/", className = "fr.imie.bankocash.soap.CrediteCompte")
    @ResponseWrapper(localName = "crediteCompteResponse", targetNamespace = "http://soap.bankocash.imie.fr/", className = "fr.imie.bankocash.soap.CrediteCompteResponse")
    public CompteEntity crediteCompte(
        @WebParam(name = "arg0", targetNamespace = "")
        CompteEntity arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Float arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<fr.imie.bankocash.soap.CompteEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCompteByEmployee", targetNamespace = "http://soap.bankocash.imie.fr/", className = "fr.imie.bankocash.soap.FindCompteByEmployee")
    @ResponseWrapper(localName = "findCompteByEmployeeResponse", targetNamespace = "http://soap.bankocash.imie.fr/", className = "fr.imie.bankocash.soap.FindCompteByEmployeeResponse")
    public List<CompteEntity> findCompteByEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns fr.imie.bankocash.soap.CompteEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createCompte", targetNamespace = "http://soap.bankocash.imie.fr/", className = "fr.imie.bankocash.soap.CreateCompte")
    @ResponseWrapper(localName = "createCompteResponse", targetNamespace = "http://soap.bankocash.imie.fr/", className = "fr.imie.bankocash.soap.CreateCompteResponse")
    public CompteEntity createCompte(
        @WebParam(name = "arg0", targetNamespace = "")
        CompteEntity arg0);

}
